# Generated by Django 5.2.1 on 2025-05-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pacientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "queixa",
                    models.CharField(
                        choices=[
                            ("TDAH", "TDAH"),
                            ("D", "Depressão"),
                            ("A", "Ansiedade"),
                            ("TAG", "Transtorno de ansiedade generalizada"),
                        ],
                        default="TDAH",
                        max_length=4,
                    ),
                ),
                ("foto", models.ImageField(upload_to="fotos")),
                ("pagamento_em_dia", models.BooleanField(default=True)),
            ],
        ),
    ]
