# Generated by Django 5.2.1 on 2025-05-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0003_tarefas_alter_pacientes_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarefas",
            options={"verbose_name": "Tarefa"},
        ),
        migrations.CreateModel(
            name="Consultas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("humor", models.PositiveIntegerField()),
                ("registro_geral", models.TextField()),
                ("video", models.FileField(upload_to="video")),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes.pacientes",
                    ),
                ),
                ("tarefas", models.ManyToManyField(to="pacientes.tarefas")),
            ],
            options={
                "verbose_name": "Consulta",
            },
        ),
    ]
